### ISSUE TITLE
AttributeError: module globus_sdk has no attribute config

### ISSUE THREAD

**Issue by sbutcher** [globus/cookiecutter-django-globus-app#6]
Following the README fails on Ubuntu 22.04 using the linked nodejs. The nodejs and npm from the repositories works though. After this step, the process fails with:

```
(venv) user@VM:~/django_globus_portal$ python manage.py migrate
Traceback (most recent call last):
  File "/home/user/venv/lib/python3.8/site-packages/globus_portal_framework/gclients.py", line 45, in get_globus_environment
    return globus_sdk.config.get_globus_environ()
  File "/home/user/venv/lib/python3.8/site-packages/globus_sdk/__init__.py", line 191, in __getattr__
    raise AttributeError(f"module {__name__} has no attribute {name}")
AttributeError: module globus_sdk has no attribute config

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/user/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/user/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/user/venv/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/user/venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 75, in handle
    self.check(databases=[database])
  File "/home/user/venv/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/home/user/venv/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/user/venv/lib/python3.8/site-packages/globus_portal_framework/checks.py", line 103, in check_globus_env
    env = get_globus_environment()
  File "/home/user/venv/lib/python3.8/site-packages/globus_portal_framework/gclients.py", line 47, in get_globus_environment
    return globus_sdk.config.get_environment_name()
  File "/home/user/venv/lib/python3.8/site-packages/globus_sdk/__init__.py", line 191, in __getattr__
    raise AttributeError(f"module {__name__} has no attribute {name}")
AttributeError: module globus_sdk has no attribute config
```
This was using v3.10 of globus-sdk.

As a workaround, downgrading to globus-sdk==2.0.3 seems to succeed

**Comment by sturoscy-personal** [comment]
The latest commit should have fixed this issue https://github.com/globus/cookiecutter-django-globus-app/commit/29324308b5d5c9218e7f3552ff9803280336a4c2. Please let us know if you encounter any other issues.
